name: Cucumber Ruby Demo
<<<<<<< HEAD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04 [Beta]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD
          ruby-version: 3.2.2
      - name: Chrome Install
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

<<<<<<< HEAD
      - name: Bundle Install
        run: bundle install

      - name: Run Cucumber Test
<<<<<<< HEAD
        run: |
          chrome --version
          chromedriver --version
          bundle exec cucumber
=======
        run: bundle exec cucumber
>>>>>>> 01cc3e9 (add Github Action workflows)
