name: Cucumber Ruby Demo
on:  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Chrome Install
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install Google Chrome and ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+(\.[0-9]+)*' | head -1)
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          echo "Downloading Chromedriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: Bundle Install
        run: bundle install

      - name: Check Chrome and ChromeDriver
        run: |
          which google-chrome
          ls -lah /usr/bin/google-chrome
          google-chrome --version
          chromedriver --version

      - name: Run Cucumber Test
        run: |
          chrome --version
          chromedriver --version
          
          HEADLESS=true bundle exec cucumber
