name: Cucumber Ruby Demo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Chrome Install
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

#       (untuk install chromedriver sesuai versi)
      - name: Install Chromedriver Automatically
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          LATEST_DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | jq -r --arg ver "$CHROME_VERSION" '.versions[] | select(.version | startswith($ver)) | .downloads.chromeDriver[] | select(.platform == "linux64") | .url')
          wget "$LATEST_DRIVER_URL" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedrive 

      - name: Bundle Install
        run: bundle install

      - name: Run Cucumber Test
        run: |
          chrome --version
          chromedriver --version
          
          HEADLESS=true bundle exec cucumber
