name: Cucumber Ruby Demo
on:  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Chrome Install
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install ChromeDriver
        run: |
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.88/linux64/chrome-linux64.zip"
          unzip -q chrome-linux64.zip
          sudo mv chrome-linux64 /opt/google/chrome
          sudo ln -s /opt/google/chrome/chrome /usr/bin/google-chrome

      - name: Bundle Install
        run: bundle install

      - name: Run Cucumber Test
        run: |
          chrome --version
          chromedriver --version
          
          HEADLESS=true bundle exec cucumber
